### PR TITLE
Absolute module reference

### PR DESCRIPTION
**Pull request by fastjames**

### CODE REVIEW

**Comment by fastjames** [comment]
I ran into this today while working on the flexi_variants extension locally.

**Review by nspinazz89 — APPROVED** [review]
🍰

**Comment by fastjames** [comment]
This may not be necessary now, I'll take a look and see. I think this was caused by a bad decorator nesting idea that I had.

**Comment by fastjames** [comment]
I don't think this is needed so I'm going to close it for now.

**Pull request closed without merging**
